<?php
// auto-generated by sfAutoloadConfigHandler
<<<<<<< HEAD
// date: 2011/12/09 13:04:46
=======
// date: 2011/12/02 15:40:00
>>>>>>> 0f5538a7f1ec1c9e23e47b93a68b02437e4e935f
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'D:/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basejobeetaffiliateformfilter' => 'D:/jobeet/lib/filter/doctrine/base/BaseJobeetAffiliateFormFilter.class.php',
  'basejobeetcategoryaffiliateformfilter' => 'D:/jobeet/lib/filter/doctrine/base/BaseJobeetCategoryAffiliateFormFilter.class.php',
  'basejobeetcategoryformfilter' => 'D:/jobeet/lib/filter/doctrine/base/BaseJobeetCategoryFormFilter.class.php',
  'basejobeetjobformfilter' => 'D:/jobeet/lib/filter/doctrine/base/BaseJobeetJobFormFilter.class.php',
  'baseformfilterdoctrine' => 'D:/jobeet/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'jobeetaffiliateformfilter' => 'D:/jobeet/lib/filter/doctrine/JobeetAffiliateFormFilter.class.php',
  'jobeetcategoryaffiliateformfilter' => 'D:/jobeet/lib/filter/doctrine/JobeetCategoryAffiliateFormFilter.class.php',
  'jobeetcategoryformfilter' => 'D:/jobeet/lib/filter/doctrine/JobeetCategoryFormFilter.class.php',
  'jobeetjobformfilter' => 'D:/jobeet/lib/filter/doctrine/JobeetJobFormFilter.class.php',
  'baseform' => 'D:/jobeet/lib/form/BaseForm.class.php',
  'basejobeetaffiliateform' => 'D:/jobeet/lib/form/doctrine/base/BaseJobeetAffiliateForm.class.php',
  'basejobeetcategoryaffiliateform' => 'D:/jobeet/lib/form/doctrine/base/BaseJobeetCategoryAffiliateForm.class.php',
  'basejobeetcategoryform' => 'D:/jobeet/lib/form/doctrine/base/BaseJobeetCategoryForm.class.php',
  'basejobeetjobform' => 'D:/jobeet/lib/form/doctrine/base/BaseJobeetJobForm.class.php',
  'baseformdoctrine' => 'D:/jobeet/lib/form/doctrine/BaseFormDoctrine.class.php',
  'jobeetaffiliateform' => 'D:/jobeet/lib/form/doctrine/JobeetAffiliateForm.class.php',
  'jobeetcategoryaffiliateform' => 'D:/jobeet/lib/form/doctrine/JobeetCategoryAffiliateForm.class.php',
  'jobeetcategoryform' => 'D:/jobeet/lib/form/doctrine/JobeetCategoryForm.class.php',
  'jobeetjobform' => 'D:/jobeet/lib/form/doctrine/JobeetJobForm.class.php',

  // project_model
  'basejobeetaffiliate' => 'D:/jobeet/lib/model/doctrine/base/BaseJobeetAffiliate.class.php',
  'basejobeetcategory' => 'D:/jobeet/lib/model/doctrine/base/BaseJobeetCategory.class.php',
  'basejobeetcategoryaffiliate' => 'D:/jobeet/lib/model/doctrine/base/BaseJobeetCategoryAffiliate.class.php',
  'basejobeetjob' => 'D:/jobeet/lib/model/doctrine/base/BaseJobeetJob.class.php',
  'jobeetaffiliate' => 'D:/jobeet/lib/model/doctrine/JobeetAffiliate.class.php',
  'jobeetaffiliatetable' => 'D:/jobeet/lib/model/doctrine/JobeetAffiliateTable.class.php',
  'jobeetcategory' => 'D:/jobeet/lib/model/doctrine/JobeetCategory.class.php',
  'jobeetcategoryaffiliate' => 'D:/jobeet/lib/model/doctrine/JobeetCategoryAffiliate.class.php',
  'jobeetcategoryaffiliatetable' => 'D:/jobeet/lib/model/doctrine/JobeetCategoryAffiliateTable.class.php',
  'jobeetcategorytable' => 'D:/jobeet/lib/model/doctrine/JobeetCategoryTable.class.php',
  'jobeetjob' => 'D:/jobeet/lib/model/doctrine/JobeetJob.class.php',
  'jobeetjobtable' => 'D:/jobeet/lib/model/doctrine/JobeetJobTable.class.php',

  // application
  'myuser' => 'D:/jobeet/apps/frontend/lib/myUser.class.php',

  // modules
);
